import { InputNumberPassThroughOptions } from "primereact/inputnumber";
import { PassThroughOptions } from "primereact/passthrough";
import { TooltipOptions } from "primereact/tooltip/tooltipoptions";
import { InputNumberValueChangeEvent } from "primereact/inputnumber";

export interface InputNumberFormProps {
  allowEmpty?: boolean;
  autoFocus?: boolean;
  buttonLayout?: "horizontal" | "vertical" | "stacked";
  currency?: string;
  currencyDisplay?: string;
  decrementButtonClassName?: string;
  decrementButtonIcon?: string;
  disabled?: boolean;
  format?: boolean;
  incrementButtonClassName?: string;
  incrementButtonIcon?: string;
  inputClassName?: string;
  inputId?: string;
  inputRef?: React.Ref<HTMLInputElement>;
  inputStyle?: React.CSSProperties;
  invalid?: boolean;
  locale?: string;
  localeMatcher?: string;
  max?: number;
  maxFractionDigits?: number;
  maxLength?: number;
  min?: number;
  minFractionDigits?: number;
  mode?: "decimal" | "currency";
  name: string;
  pattern?: string;
  placeholder?: string;
  prefix?: string;
  pt?: InputNumberPassThroughOptions;
  ptOptions?: PassThroughOptions | null;
  readOnly?: boolean;
  required?: boolean;
  roundingMode?: string;
  showButtons?: boolean;
  size?: number;
  step?: number;
  suffix?: string;
  tabIndex?: number;
  tooltip?: string;
  tooltipOptions?: TooltipOptions | null;
  type?: string;
  unstyled?: boolean;
  useGrouping?: boolean;
  value?: number | null;
  variant?: "filled" | "outlined";
  id: string;
  group?: boolean;
  leftAddon?: string;
  leftAddonType?: "icon" | "text";
  rightAddon?: string;
  rightAddonType?: "icon" | "text";
  label?: string;
  onChange?: (event: InputNumberValueChangeEvent) => void;
  errors?: string[];
}
