import ToastComponent from "@components/form/toasts/toast.component";
import type { Metadata } from "next";
import "./globals.css";
import { PrimeReactProvider } from "primereact/api";
import { ToastProvider } from "@contexts/toast/toast.context";
import { LoadingProvider } from "@contexts/loading/loading.context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              const style = document.createElement('style')
              style.innerHTML = '@layer tailwind-base, primeReact, tailwind-utilities;'
              style.setAttribute('type', 'text/css')
              document.querySelector('head').prepend(style)
            `,
          }}
        />
      </head> */}
      <body>
        <PrimeReactProvider>
          <ToastProvider>
            <LoadingProvider>
              <ToastComponent />
              {children}
            </LoadingProvider>
          </ToastProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
